name: matrix demo
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [12,14,16]
                operating-systems: [ubuntu-latest,windows-latest]
        runs-on: ${{matrix.operating-systems}}
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install node js
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}
            - name: install dependancies
              run: npm install
            - name: build project
              run: npm run build
